name: AE project (UI-run spec. test)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2g
        env:
          SE_SCREEN_WIDTH: 1920
          SE_SCREEN_HEIGHT: 1080
          SE_SCREEN_DEPTH: 24
          SE_SCREEN_DPI: 96
          

    steps:
      - uses: actions/checkout@v4

     # 1. Подготовка окружения
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.10'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Debug secrets value
        run: |
         echo "baseUrl=${{ secrets.BASEURL }}"
         echo "guest.header.authorization=${{ secrets.GUEST_AUTHORIZATION }}"

      - name: Debug browser size
        run: |
         echo "Browser width: ${{ inputs.browserWidth || '1920' }}"
         echo "Browser height: ${{ inputs.browserHeight || '1080' }}"

      - name: Verify test execution
        run: |
          echo "1. Максимальное число worker-ов:"
          ./gradlew --max-workers=1 --quiet properties | grep -E 'maxWorkers|org.gradle.workers.max' || echo "Не найдено"
    
          echo "2. Параметры JUnit:"
          ./gradlew --quiet test -m | grep -i 'junit' || echo "Параметры JUnit не найдены"

      - name: Debug secret
        run: |
         echo "AUTH_TOKEN: $AUTH_TOKEN"
        env:
         AUTH_TOKEN: ${{ secrets.GUEST_AUTHORIZATION }}

      - name: Run API Tests
        env:
          BASE_URL: ${{ secrets.BASEURL }}
          GUEST_AUTH: ${{ secrets.GUEST_AUTHORIZATION }}
        run: |
          ./gradlew apiTest --tests "ui.pages.FastShopPageTests"\
            -Dmode=GUEST \
            -DbaseUrl="$BASE_URL" \
            -Dguest.header.authorization="$GUEST_AUTH" \
            --stacktrace \
            --info

      - name: Run UI Tests
        run: |
         ./gradlew uiTest \
         --no-parallel \
         --max-workers=1 \
         -Dorg.gradle.workers.max=1 \
         -DitemsCount=10 \
         -Dselenium.remote.url=http://localhost:4444/wd/hub \
         -Dbrowser.width=1920 \
         -Dbrowser.height=1080
        

      - name: Copy History
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Report
        if: always()
        uses: simple-elf/allure-report-action@v1.10
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
