name: AE project (API and UI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: >-
          --shm-size 2g
          -e SE_SCREEN_WIDTH=1920
          -e SE_SCREEN_HEIGHT=1080
          -e SE_SCREEN_DEPTH=24
          -e SE_SCREEN_DPI=96
          

    steps:
      - uses: actions/checkout@v4

     # 1. Подготовка окружения
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.10'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Debug secrets value
        run: |
          echo "baseUrl=${{ secrets.BASE_URL }}"
          echo "guest.header.authorization=${{ secrets.GUEST_AUTHORIZATION }}"

      - name: Run Tests
        env:
          BASEURL: ${{ secrets.BASEURL }}
          GUEST_HEADER_AUTHORIZATION: ${{ secrets.GUEST_AUTHORIZATION }}"
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}"
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}"
        run: |
         ./gradlew test \
         -Dmode=GUEST \
         -Dselenium.remote.url=http://localhost:4444/wd/hub   


      - name: Copy History
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Report
        if: always()
        uses: simple-elf/allure-report-action@v1.10
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history