name: AE project (API and UI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: >-
          --shm-size 2g
          -e SE_SCREEN_WIDTH=1920
          -e SE_SCREEN_HEIGHT=1080

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # 1. Подготовка окружения
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.10'

      - name: Prepare Properties Files
        run: |
            mkdir -p src/test/resources/properties
            # Для GUEST-режима
            echo "mode=GUEST" > src/test/resources/properties/guest.properties
            echo "baseUrl=${{ secrets.BASE_URL }}" >> src/test/resources/properties/guest.properties
            echo "guest.header.authorization=${{ secrets.GUEST_AUTHORIZATION }}" >> src/test/resources/properties/guest.properties
            # Для AUTH-режима
            echo "mode=AUTH" > src/test/resources/properties/auth.properties
            echo "baseUrl=${{ secrets.BASE_URL }}" >> src/test/resources/properties/auth.properties
            echo "auth.username=${{ secrets.AUTH_USERNAME }}" >> src/test/resources/properties/auth.properties
            echo "auth.password=${{ secrets.AUTH_PASSWORD }}" >> src/test/resources/properties/auth.properties

      - name: Run Tests
        run: |
            ./gradlew clean test \
            -Dmode=GUEST \  # Или AUTH
            -Dselenium.remote.url=http://localhost:4444/wd/hub    


      - name: Copy History
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Report
        if: always()
        uses: simple-elf/allure-report-action@v1.10
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history