name: AE project (API and UI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g
          -e SE_SCREEN_WIDTH=1920
          -e SE_SCREEN_HEIGHT=1080
          -e SE_SCREEN_DEPTH=24
          -e SE_START_XVFB=false
          -e SE_VNC_NO_PASSWORD=1
          -e SE_NO_VNC_PORT=7900
        ports:
          - 4444:4444  # Selenium Grid
          - 7900:7900  # VNC (для просмотра сессий)

    strategy:
      matrix:
        mode: [GUEST, AUTH]
        include:
          - mode: GUEST
            report_name: "Guest Mode Report"
          # - mode: AUTH
          #   report_name: "Auth Mode Report"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.10'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Configure test properties

        run: |
          mkdir -p src/test/resources/properties
          if [ "${{ matrix.mode }}" = "GUEST" ]; then
            echo "mode=GUEST" > src/test/resources/properties/guest.properties
            echo "baseUrl=${{ secrets.BASE_URL }}" >> src/test/resources/properties/guest.properties
            echo "guest.header.authorization=${{ secrets.GUEST_AUTHORIZATION }}" >> src/test/resources/properties/guest.properties
          else
            echo "mode=AUTH" > src/test/resources/properties/auth.properties
            echo "baseUrl=${{ secrets.BASE_URL }}" >> src/test/resources/properties/auth.properties
            echo "auth.username=${{ AUTH_USERNAME }}" >> src/test/resources/properties/auth.properties
            echo "auth.password=${{ AUTH_PASSWORD }}" >> src/test/resources/properties/auth.properties
          fi

      - name: Run tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          #System properties
        run: ./gradlew clean test -Dselenium.remote.url=$SELENIUM_REMOTE_URL \
          -Dmode='GUEST' \
          -DbaseUrl=${{ secrets.BASE_URL }} \
          -Dguest.header.authorization=${{ secrets.GUEST_AUTHORIZATION }}

      - name: Copy History
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history