name: AE project (API and UI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        volumes:
          - ./videos:/opt/selenium/videos
        environment:
          - SE_RECORD_VIDEO=true
          - SE_VIDEO_FILE_NAME=test_${GITHUB_RUN_ID}.mp4  # Уникальное имя файла
        options: >-
          --shm-size 2g
          -e SE_SCREEN_WIDTH=1920
          -e SE_SCREEN_HEIGHT=1080
          -e SE_SCREEN_DEPTH=24
          -e SE_START_XVFB=false
          -e SE_VNC_NO_PASSWORD=1
          -e SE_NO_VNC_PORT=7900
        ports:
          - 4444:4444
          - 7900:7900

    steps:
      - uses: actions/checkout@v4

      # 1. Подготовка окружения
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.10'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # 2. Подготовка тестовых данных
      - name: Create videos directory
        run: |
          mkdir -p ./videos
          chmod 777 ./videos  # Права нужно дать ДО запуска контейнера

      - name: Configure test properties
        run: |
          mkdir -p src/test/resources/properties
          echo "mode=GUEST" > src/test/resources/properties/guest.properties
          echo "baseUrl=${{ secrets.BASE_URL }}" >> src/test/resources/properties/guest.properties
          echo "guest.header.authorization=${{ secrets.GUEST_AUTHORIZATION }}" >> src/test/resources/properties/guest.properties

      # 3. Запуск тестов
      - name: Run tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          SECRET_BASE_URL: ${{ secrets.BASE_URL }}
          SECRET_GUEST_AUTH: ${{ secrets.GUEST_AUTHORIZATION }}
        run: |
          echo "Running tests with:"
          echo "Selenium URL: $SELENIUM_REMOTE_URL"
          
          ./gradlew clean test \
            -Dselenium.remote.url="$SELENIUM_REMOTE_URL" \
            -Dmode="GUEST" \
            -DbaseUrl="$SECRET_BASE_URL" \
            -Dguest.header.authorization="$SECRET_GUEST_AUTH" \
            -Dheadless=true

      # 4. Пост-обработка
      - name: Debug videos folder
        if: always()
        run: |
          echo "Videos directory content:"
          ls -la ./videos

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-videos
          path: ./videos/*.*
          retention-days: 3  # Автоочистка через 3 дня

      - name: Copy History
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Report
        if: always()
        uses: simple-elf/allure-report-action@v1.10
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history